# Generated by Django 3.2 on 2021-07-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staffid',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
