# Generated by Django 3.1.1 on 2021-07-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('zhicheng', models.CharField(max_length=20)),
                ('keshi', models.CharField(max_length=20)),
                ('gangwei', models.CharField(max_length=20)),
                ('kss', models.IntegerField()),
                ('duma', models.CharField(max_length=20)),
                ('fsyp', models.CharField(max_length=20)),
                ('yljs', models.CharField(max_length=20)),
                ('eljs', models.CharField(max_length=20)),
                ('xkyp', models.CharField(max_length=20)),
                ('mzqx', models.CharField(max_length=20)),
                ('bz', models.CharField(max_length=200)),
            ],
        ),
    ]
