# Generated by Django 3.2 on 2021-08-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinfo',
            name='jindu',
            field=models.CharField(default='待开通', max_length=5),
        ),
    ]
